name: pycoistats
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >= 3.6
  - pandas
  - os
  - argparse
  - biopython
  - collections
  - itertools
  - pathlib
  - matplotlib
  - seaborn
  - csvkit
  - jupyter