package:
  name: pycoistats
  version: 1.4

source:
  git_rev: v1.4
  git_url: https://github.com/cdoorenweerd/PyCOIStats

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - python >=3.6
    - pandas
    - biopython
    - pathlib
    - matplotlib
    - seaborn
    - csvkit
    - jupyter
    - setuptools
    - scikit-bio
about:
  home: https://github.com/cdoorenweerd/PyCOIStats
  license: GPL-3.0
  summary: "Calculate haploid DNA sequence alignment statistics"