package:
  name: pycoistats
  version: 1.3.1

source:
  git_rev: v1.3.1
  git_url: https://github.com/cdoorenweerd/PyCOIStats

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - add all packages here
about:
  home: https://github.com/cdoorenweerd/PyCOIStats
  license: GPL-3.0
  summary: "Calculate haploid DNA sequence alignment statistics"